services:
  db:
    image: postgres:15
    container_name: lms_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    restart: always
  # backend:
  #   build:
  #     context: ./backend/lms-backend
  #     dockerfile: ./src/main/docker/Dockerfile
  #   container_name: lms_backend
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   restart: always

volumes:
  postgres_data:
